# *******************************************************************************
# Copyright 2024-2025 Arm Limited and affiliates.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# *******************************************************************************

name: Coverity Scan

# on:
#   schedule:
#     #* set to run each Friday at 12:00 UTC
#     - cron: '0 12 * * 5'
#   #* allows this workflow to be invoked by another workflow
#   workflow_call:
#   #* allows manual trigger of workflow when needed
#   workflow_dispatch:

on:
# Only run on push to main branch
  push:
    branches: [dev/vyevtyus/cov_enabling]
  workflow_call:
  #* allows manual trigger of workflow when needed
  workflow_dispatch:

permissions: read-all

env:
  COVERITY_PROJECT: vyevtyus%2FoneMKL-samples
  COVERITY_PROJECT_ID: 32889

jobs:
  coverity_linux:
    name: Coverity Linux
    if: github.repository == 'vyevtyus/oneMKL-samples'
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Download Coverity Build Tool (linux64)
        run: |
          curl --fail https://scan.coverity.com/download/cxx/linux64 --output ${GITHUB_WORKSPACE}/cov-linux64-tool.tar.gz \
            --data "token=${{secrets.COVERITY_TOKEN}}&project=${{env.COVERITY_PROJECT}}" || { echo "Download failed"; exit 1; }
          mkdir cov-linux64-tool
          tar -xzf cov-linux64-tool.tar.gz --strip 1 -C cov-linux64-tool
          cd cov-linux64-tool/config
          git apply --check ${GITHUB_WORKSPACE}/.github/workflows/fix.coverity-2024.12.patch
          if patch -p1 < ${GITHUB_WORKSPACE}/.github/workflows/fix.coverity-2024.12.patch; then
            echo "Coverity Build Tool configs successfully patched"
          else
            echo "Coverity Build Tool configs patching failed, check patch relevance to current Coverity Build Tool version"
            exit 1
          fi

      - name: Download Intel compiler
        run: |
          wget --progress=dot:giga https://registrationcenter-download.intel.com/akdlm/IRC_NAS/5adfc398-db78-488c-b98f-78461b3c5760/intel-dpcpp-cpp-compiler-2025.3.1.16_offline.sh
          sudo bash intel-dpcpp-cpp-compiler-2025.3.1.16_offline.sh -s -a -s --action install --eula accept

      - name: Install Intel oneMKL
        run: |
          wget --progress=dot:giga https://registrationcenter-download.intel.com/akdlm/IRC_NAS/2ad98b49-1fb2-4294-ab3d-6889b434ebd3/intel-onemkl-2025.3.0.462_offline.sh
          sudo bash intel-onemkl-2025.3.0.462_offline.sh -s -a -s --action install --eula accept --install-dir /opt/intel/mkl

      - name: Prepare and run Coverity build
        run: |
          source /opt/intel/oneapi/setvars.sh
          source /opt/intel/mkl/mkl/latest/env/vars.sh
          export PATH="${PWD}/cov-linux64-tool/bin:${PATH}"
          cov-configure --template --compiler icpx --comptype intel_icpx:linux
          ls -la

          shopt -s nullglob
          GLOBIGNORE="american_options:batched_linear_solver:cov-int:*git*"

          for d in */; do
            echo ">> $d"
            (cd "$d" && cov-build --dir ../cov-int --append-log --delete-stale-tus make || [[ $? -eq 2 ]])
          done

      - name: Archive oneMKL-samples build results
        run: |
          tar -czf cov-int.tgz cov-int
          size=$(du -m cov-int.tgz | cut -f1)
          echo "Artifact size: $size MB"
          echo "size=$size" >> $GITHUB_OUTPUT

      - name: Cache build archive
        uses: actions/cache@v4
        with:
          path: cov-int.tgz
          key: oneMKL-samples-cov-dir-${{github.sha}}

      # - name: Submit Coverity results for analysis
      #   run: |
      #     cd build
      #     curl -X POST \
      #       -d version="${GITHUB_SHA}" \
      #       -d description="" \
      #       -d email="${{secrets.COVERITY_EMAIL}}" \
      #       -d token="${{secrets.COVERITY_TOKEN}}" \
      #       -d file_name=@cov-int.tgz \
      #       https://scan.coverity.com/projects/${{env.COVERITY_PROJECT_ID}}/builds/init \
      #       | tee response
      #     upload_url=$(jq -r '.url' response)
      #     if [ -z "$upload_url" ] || [ "$upload_url" == "null" ]; then
      #       echo "Error: Failed to extract 'url' from API response." >&2
      #       cat response >&2
      #       exit 1
      #     fi
      #     build_id=$(jq -r '.build_id' response)
      #     curl -X PUT \
      #       --header 'Content-Type: application/json' \
      #       --upload-file cov-int.tgz \
      #       $upload_url
